---
title: "Simulator Validation (TCC)"
author: "David Ferreira Quaresma (david.quaresma@ccc.ufcg.edu.br)"
date: "april, 2021"
output: pdf_document
---

# LOAD DATA
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
result_path = "/home/david/TCC/TCC/results/"
require(dplyr)
read.al <- function(path) {
  df <- read.csv(path, sep=",",header=T, dec=".")
  return (df)
}
remove_warmup <- function(data, warmup_value=0) {
  if (warmup_value == 0) {
    return(data)
  } else {
    return(tail(data, -warmup_value))
  }
}

warmup = 1000
head_size = 20000

measurements = "NULL"
for (id in 1:4) {
  for (lambda in c(20)) {
    path = paste(result_path, "measurements/MEASUREMENTS_20000/measurement-lambda", lambda, "-", id, ".csv", sep="")
    measurement = read.al(path)
    measurement = remove_warmup(head(measurement, head_size), warmup)
    measurement$response_time = measurement$response_time / 1000000
    measurement$service_time = measurement$body / 1000000
    measurement$tag = paste("measurement-lambda", lambda, "-id", id, sep="")
    measurement$lambda = lambda
    if (measurements == "NULL") {
      measurements = measurement
    } else {
      measurements = rbind(measurements, measurement)
    }
  }
}
rm(measurement)

simulations = "NULL"
for (id in 1:4) {
  for (lambda in c(20)) {
    path = paste(result_path, "simulation/sim-lambda", lambda, "-idleness300s-warmup0-id", id, "-normscheduler-reqs.csv", sep="")
    simulation = read.al(path)
    simulation = remove_warmup(head(simulation, head_size), warmup)
    simulation$response_time = simulation$response_time * 1000
    simulation$service_time = simulation$response_time
    simulation$tag = paste("simulation-lambda", lambda, "-id", id, sep="")
    simulation$lambda = lambda
    if (simulations == "NULL") {
      simulations = simulation
    } else {
      simulations = rbind(simulations, simulation)
    }
  }
}
rm(simulation)

warmup = 250

inputs = "NULL"
for (id in 1:32) {
  path = paste(result_path, "measurements/INPUT_5000/input-lambda0-", id, ".csv", sep="")
  input = read.al(path)
  input = remove_warmup(input, warmup)
  input$response_time = input$response_time / 1000000
  input$service_time = input$body / 1000000
  input$tag = paste("input-", "-id", id, sep="")
  if (inputs == "NULL") {
    inputs = input
  } else {
    inputs = rbind(inputs, input)
  }
}
rm(input)

paste("Measurement cold starts:", NROW(filter(measurements, service_time > 500)))
paste("Simulation cold starts:", NROW(filter(simulations, service_time > 500)))
paste("Inputs cold starts:", NROW(filter(inputs, service_time > 500)))

# measurements = filter(measurements, service_time < 500)
# simulations = filter(simulations, service_time < 500)
# inputs = filter(inputs, service_time < 500)

measurements$service_time = round(measurements$service_time, digits=2)
simulations$service_time = round(simulations$service_time, digits=2)
inputs$service_time = round(inputs$service_time, digits=2)

# tss = filter(simulations, tag=="simulation-lambda20-id1")
# tmp2 = read.al("/home/david/TCC/TCC/results/simulation/sim-lambda20-idleness300s-warmup0-id1-normscheduler-instances.csv")
# tmp = read.al("/home/david/TCC/TCC/results/measurements/measurement-lambda0-test.csv")
# rm(tss, tmp, tmp2)
```

# ECDF VISUAL TEST
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
require(quantileCI)
ecdf_plot <- function(title, data, xinf, xsup, yinf, ysup, linetype=c("solid", "dotted", "dashed"), cols=c(15, 195, 150), img_name=FALSE) {
    simulation.color <- "blue"
    simulation.p999 <- quantile(data$simulation, 0.999)
    simulation.p50 <- quantile(data$simulation, 0.5)
    measurement.color <- "red"
    measurement.p999 <- quantile(data$measurement, 0.999)
    measurement.p50 <- quantile(data$measurement, 0.5)
    inputs.color <- "green"
    inputs.p999 <- quantile(data$inputs, 0.999)
    inputs.p50 <- quantile(data$inputs, 0.5)

    annotate_y = 0.9
    size = 0.5
    alpha = 0.8
    angle = 90
    
    p <- data[, colSums(is.na(data)) != nrow(data)] %>%
    pivot_longer(everything()) %>%
    group_by(name) %>%
    arrange(value, by_group = TRUE) %>%
    mutate(ecdf = seq(1/n(), 1 - 1/n(), length.out = n())) %>%
    ggplot(aes(x = value, y = ecdf, colour=name, linetype=name)) +
    xlim(xinf, xsup) +
    ylim(yinf, ysup) +
    geom_step() +
    theme(text=element_text(size=12), plot.title = element_text(hjust = 0.5))+
    theme(legend.text=element_text(size=12)) +
    theme(legend.position="top") +

      
    scale_color_manual(values=c("green", "red", "blue")) +  
    scale_fill_manual(values=hcl(100, 65, alpha=c(1, 1, 1))) +
    scale_linetype_manual(values=linetype) +
    labs(x="Response Time (ms)",y="ECDF", color="scenario", linetype="scenario") +
    ggtitle(title) +

    # P50
    annotate(geom="text", x=simulation.p50, y=annotate_y, label="Median", angle=angle, color=simulation.color) +
    geom_vline(xintercept=simulation.p50, linetype="dashed", size=size, alpha=alpha, color=simulation.color) +
    annotate(geom="text", x=measurement.p50, y=annotate_y, label="Median", angle=angle, color=measurement.color) +
    geom_vline(xintercept=measurement.p50, linetype="dotted", size=size, alpha=alpha, color=measurement.color) +
    annotate(geom="text", x=inputs.p50, y=annotate_y, label="Median", angle=angle, color=inputs.color) +
    geom_vline(xintercept=inputs.p50, linetype="solid", size=size, alpha=alpha/2, color=inputs.color) +

    # P999
    annotate(geom="text", x=simulation.p999, y=annotate_y, label="99.9th", angle=angle, color=simulation.color) +
    geom_vline(xintercept=simulation.p999, linetype="dashed", size=size, alpha=alpha, color=simulation.color) +
    annotate(geom="text", x=measurement.p999, y=annotate_y, label="99.9th", angle=angle, color=measurement.color) +
    geom_vline(xintercept=measurement.p999, linetype="dotted", size=size, alpha=alpha, color=measurement.color) +
    annotate(geom="text", x=inputs.p999, y=annotate_y, label="99.9th", angle=angle, color=inputs.color) +
    geom_vline(xintercept=inputs.p999, linetype="solid", size=size, alpha=alpha/2, color=inputs.color) +

      
    theme_bw()
        
    if (img_name != FALSE) {
      ggsave(img_name, width=10, height=5)
    }
    print(p)
}

measurement = filter(measurements, lambda == 20)
simulation = filter(simulations, lambda == 20)

# ecdf_plot("VERIFYING RESULTS", data.frame(
#   measurement = measurement$service_time,
#   simulation  = simulation$service_time,
#   inputs      = inputs$service_time
# ), 10, 25, 0, 0.5)
# 
# 
# ecdf_plot("VERIFYING RESULTS", data.frame(
#   measurement = measurements$service_time,
#   simulation  = simulations$service_time,
#   inputs      = inputs$service_time
# ), 20, 50, 0.5, 1)

ecdf_plot("Comparison of ECDF Curves of Experiments", data.frame(
  measurement = measurements$service_time,
  simulation  = simulations$service_time,
  inputs      = inputs$service_time
), 10, 100, 0, 1), img_name="results-ecdf.png")

rm(measurement, simulation)
```

# BOXPLOT VISUAL TEST
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
boxplot_plot <- function(title, df_a, df_b, df_c, yrange, outliershape = NA) {
  return(ggplot(rbind(df_a, df_b, df_c), aes(x=scenario, y=service_time, fill=scenario)) +
  geom_boxplot(outlier.shape = outliershape) +
  scale_fill_manual(values=hcl(c(15, 195, 150), 100, 65, alpha=c(0.5, 1))) +
  coord_cartesian(ylim=yrange) + 
  theme(text=element_text(size=15)) +
  theme(legend.text=element_text(size=15)) +
  labs(x = "scenario", y = "indexing duration (ms)") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), axis.title.x = element_blank(), plot.title = element_text(hjust = 0.5)) +
  theme_bw() +
  ggtitle(title)
  )
}

measurement = filter(measurements, lambda == 20)
simulation = filter(simulations, lambda == 20)
df_sim_to_boxplot = data.frame(scenario = "sim", service_time = simulation$service_time)
df_mean_to_boxplot = data.frame(scenario = " mea", service_time = measurement$service_time)
df_imp_to_boxplot = data.frame(scenario = "imp", service_time = inputs$service_time)
boxplot_plot("Lambda 20", df_mean_to_boxplot, df_sim_to_boxplot, df_imp_to_boxplot, c(10, 50))

rm(df_sim_to_boxplot, df_mean_to_boxplot, df_imp_to_boxplot)
rm(measurement, simulation)
```


# IDENTIFYING DISTRIBUTION
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(fitdistrplus)
measurement = filter(measurements, lambda == 20)
png("results-cullen-frey-graph-measurements_2.png", width=5, height=5, units="in", res=1200) 
descdist(measurement$service_time, discrete = FALSE, boot=2000)
dev.off()
hist(measurement$service_time, freq = FALSE)
lines(density(measurement$service_time))

simulation = filter(simulations, lambda == 20)
png("results-cullen-frey-graph-simulations_2.png", width=5, height=5, units="in", res=1200) 
descdist(simulation$service_time, discrete = FALSE, boot=2000)
dev.off()
hist(simulation$service_time, freq = FALSE)
lines(density(simulation$service_time))

# descdist(inputs$service_time, discrete = FALSE, boot=2000)
# hist(inputs$service_time, freq = FALSE)
# lines(density(inputs$service_time))

rm(measurement, simulation)
```


# PLOT CI TABLE
```{r setup, include=FALSE}
require(dplyr)
require(ggplot2)
library(ggpubr)
require(quantileCI)
require(base64enc)
summary_table <- function(df1, tag1, df2, tag2) {
  qCI <- function(df, p) {
    return(quantileCI::quantile_confint_nyblom(df, p))
  }
  stats <- function(df) {
    avg = signif(t.test(df)$conf.int, digits = 2)
    p50 = signif(qCI(df, 0.5), digits = 4)
    p95 = signif(qCI(df, 0.95), digits = 4)
    p99 = signif(qCI(df, 0.99), digits = 4)
    p999 = signif(qCI(df, 0.999), digits = 4)
    # p9999 = signif(qCI(df, 0.9999), digits = 4)
    # p99999 = signif(qCI(df, 0.99999), digits = 4)
    # dist = signif(qCI(df, 0.99999)- qCI(df, 0.5), digits = 4)
    data <- c(avg, p50, p95, p99, p999)#, p9999, p99999, dist)
    return(data)
  }

  stats1 = stats(df1)
  stats2 = stats(df2)
  avgdf    <- data.frame("avg",    stats1[1],  stats1[2],  stats2[1],  stats2[2])
  p50df    <- data.frame("p50",    stats1[3],  stats1[4],  stats2[3],  stats2[4])
  p95df    <- data.frame("p95",    stats1[5],  stats1[6],  stats2[5],  stats2[6])
  p99df    <- data.frame("p99",    stats1[7],  stats1[8],  stats2[7],  stats2[8])
  p999df   <- data.frame("p999",   stats1[9],  stats1[10], stats2[9],  stats2[10])
  # p9999df  <- data.frame("p9999",  stats1[11], stats1[12], stats2[11], stats2[12])
  # p99999df <- data.frame("p99999", stats1[13], stats1[14], stats2[13], stats2[14])
  # distdf   <- data.frame("dist",   stats1[15], stats1[16], stats2[15], stats2[16])

  tag1_inf = paste(tag1, "cii", sep = ".")
  tag1_sup = paste(tag1, "cis", sep = ".")
  tag2_inf = paste(tag2, "cii", sep = ".")
  tag2_sup = paste(tag2, "cis", sep = ".")
  names(avgdf)    <- c("stats", tag1_inf, tag1_sup, tag2_inf, tag2_sup)
  names(p50df)    <- c("stats", tag1_inf, tag1_sup, tag2_inf, tag2_sup)
  names(p95df)    <- c("stats", tag1_inf, tag1_sup, tag2_inf, tag2_sup)
  names(p99df)    <- c("stats", tag1_inf, tag1_sup, tag2_inf, tag2_sup)
  names(p999df)   <- c("stats", tag1_inf, tag1_sup, tag2_inf, tag2_sup)
  # names(p9999df)  <- c("stats", tag1_inf, tag1_sup, tag2_inf, tag2_sup)
  # names(p99999df) <- c("stats", tag1_inf, tag1_sup, tag2_inf, tag2_sup)
  # names(distdf)   <- c("stats", tag1_inf, tag1_sup, tag2_inf, tag2_sup)
  df <- rbind(avgdf, p50df, p95df, p99df, p999df)#, p9999df, p99999df, distdf)
  df
}
measurement = filter(measurements, lambda == 20)
simulation = filter(simulations, lambda == 20)

summary_table(measurement$service_time, "measurement", simulation$service_time,"simulation")
summary_table(measurement$service_time, "measurement", inputs$service_time,"inputs")
summary_table(inputs$service_time, "inputs", simulation$service_time,"simulation")


rm(measurement, simulation)

mean(simulations$service_time)
mean(inputs$service_time)
mean(measurements$service_time)
```

# STATISTICAL SAMPLE TEST
```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
tmp = rbind(
  data.frame(service_time = sample(measurements$service_time, 70000), group = "measurement"),
  data.frame(service_time = sample(simulations$service_time, 70000), group = "simulation"),
  data.frame(service_time = sample(inputs$service_time, 70000), group = "input")
)
kruskal.test(service_time ~ group, tmp) # http://www.sthda.com/english/wiki/kruskal-wallis-test-in-r and https://stat-methods.com/home/kruskal-wallis-r/

pairwise.wilcox.test(tmp$service_time, tmp$group,
                 p.adjust.method = "BH")


rm(tmp)
### DEPRECATED
# measurement = sample(filter(measurements, lambda == 20)$service_time, 100)
# simulation = sample(filter(simulations, lambda == 20)$service_time, 100)
# library(kSamples)
# ad.test(measurement, simulation)
# ks.test(measurement, simulation)
# measurement_1 = sample(filter(measurements, tag == "measurement-lambda20-id1")$service_time, 100)
# measurement_2 = sample(filter(measurements, tag == "measurement-lambda20-id4")$service_time, 100)
# ad.test(measurement_1, measurement_2)
# ks.test(measurement_1, measurement_2)
# wilcox.test(measurement, simulation, alt = "two.sided", mu=0, paired=FALSE, conf.int=T, paired=F, conf.level=0.95, exact=T, correct=T)
# require(BWStest)
# bws_test(measurement, simulation)
# t.test(measurement, simulation)
# plot(ecdf(filter(simulations, lambda == 20)$service_time))
# lines(ecdf(filter(measurements, lambda == 20)$service_time), col='red')
# about validation: https://www.scielo.br/scielo.php?script=sci_arttext&pid=S0101-74382011000100005
# rm(measurement, simulation)
```
